# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20171211_1519'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookings',
            unique_together=set([('room', 'date', 'time_id')]),
        ),
    ]
